spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/samuraitravel_db
spring.datasource.username=root
spring.datasource.password=Yume9813!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.encoding=utf-8
spring.sql.init.mode=always

spring.servlet.multipart.max-file-size=5MB

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=6adc5f97c3d04f
spring.mail.password=2b1b9e5fb5ba47
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

stripe.api-key=sk_test_51RLyjQQ5pSbhhYlHJb4BbrUjwXT0W7ugoK5mce6rNwkJymUwrCfyB1pXCrKZKV3fPO1bczKIsn1hsIh7Odkgegn800OPGptNKv
stripe.webhook-secret=710f0129b50125488e5522e41a3b4c536c058594a25
debug=true